import { ScrollView, StatusBar, StyleSheet, Text, View } from 'react-native';

const items=[
 {name:'Telegram',state:'Подключён',ok:true,detail:'MasterPick Georgia и бот'},
 {name:'GitHub',state:'Подключён',ok:true,detail:'Репозитории и сборка приложения'},
 {name:'Expo / EAS',state:'Подключён',ok:true,detail:'Android APK собирается в облаке'},
 {name:'YouTube',state:'Требует подключения',detail:'Нужна авторизация/API'},
 {name:'Instagram',state:'Требует подключения',detail:'Нужен рабочий аккаунт Meta'},
 {name:'Pinterest',state:'Требует подключения',detail:'Аккаунт есть, API не связан'},
];
export default function Settings(){return <View style={s.screen}><StatusBar barStyle="light-content" backgroundColor="#0b1220"/><ScrollView contentContainerStyle={s.content}><Text style={s.kicker}>НАСТРОЙКИ</Text><Text style={s.title}>Подключения</Text><Text style={s.subtitle}>Состояние сервисов Master Hub. Секретные ключи в приложении не отображаются и не хранятся.</Text>{items.map(i=><View key={i.name} style={s.card}><View style={s.row}><View style={s.left}><View style={[s.dot,i.ok?s.good:s.wait]}/><View><Text style={s.name}>{i.name}</Text><Text style={s.detail}>{i.detail}</Text></View></View><Text style={[s.state,i.ok?s.stateGood:s.stateWait]}>{i.state}</Text></View></View>)}<View style={s.security}><Text style={s.securityTitle}>Безопасность</Text><Text style={s.securityText}>Токены Telegram, GitHub, OpenAI и партнёрских сервисов должны оставаться на сервере или в защищённых секретах. В APK будут только интерфейс и безопасные запросы к backend.</Text></View><View style={s.next}><Text style={s.nextTitle}>Каркас Master Hub готов</Text><Text style={s.nextText}>Следующий технический этап — backend API. Он позволит приложению реально запускать публикации, читать статусы и получать аналитику.</Text></View></ScrollView></View>}
const s=StyleSheet.create({screen:{flex:1,backgroundColor:'#0b1220'},content:{padding:20,paddingTop:34,paddingBottom:40},kicker:{color:'#38bdf8',fontWeight:'800',letterSpacing:2,fontSize:13},title:{color:'#fff',fontSize:30,fontWeight:'800',marginTop:7},subtitle:{color:'#94a3b8',fontSize:15,lineHeight:22,marginTop:8,marginBottom:22},card:{backgroundColor:'#111c2e',borderRadius:17,padding:16,marginBottom:11,borderWidth:1,borderColor:'#22304a'},row:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:10},left:{flexDirection:'row',alignItems:'center',gap:11,flex:1},dot:{width:10,height:10,borderRadius:5},good:{backgroundColor:'#22c55e'},wait:{backgroundColor:'#f59e0b'},name:{color:'#fff',fontSize:16,fontWeight:'800'},detail:{color:'#8494aa',fontSize:12,marginTop:4},state:{fontSize:11,fontWeight:'800',maxWidth:95,textAlign:'right'},stateGood:{color:'#86efac'},stateWait:{color:'#fcd34d'},security:{backgroundColor:'#172554',borderRadius:18,padding:18,marginTop:10},securityTitle:{color:'#bfdbfe',fontSize:15,fontWeight:'800'},securityText:{color:'#dbeafe',fontSize:14,lineHeight:21,marginTop:7},next:{backgroundColor:'#111c2e',borderRadius:18,padding:18,marginTop:13,borderWidth:1,borderColor:'#22304a'},nextTitle:{color:'#fff',fontSize:17,fontWeight:'800'},nextText:{color:'#94a3b8',fontSize:14,lineHeight:21,marginTop:7}});
